# Generated by Django 3.2.8 on 2021-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplatform',
            name='platform_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
