# Generated by Django 3.2.9 on 2021-11-11 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergenre',
            unique_together={('user', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='userplatform',
            unique_together={('user', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='userpublisher',
            unique_together={('user', 'publisher')},
        ),
    ]
