# Generated by Django 3.2.9 on 2021-11-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20211111_1534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergenre',
            table='user_genre',
        ),
        migrations.AlterModelTable(
            name='userplatform',
            table='user_platform',
        ),
        migrations.AlterModelTable(
            name='userpublisher',
            table='user_publisher',
        ),
    ]
