# Generated by Django 3.2.9 on 2021-11-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tier_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
