# Generated by Django 3.2.9 on 2021-11-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
        ('authentication', '0002_auto_20211109_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tier_level',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.boxtier'),
        ),
    ]
